/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pilasejercicio;

import javax.swing.JOptionPane;

/**
 *
 * @author SCIS2-19
 */
public class Vista extends javax.swing.JFrame {
    PilasEjercicio pila = new PilasEjercicio();
    int i = -1;
    int i2 = -1;
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarPila = new javax.swing.JButton();
        imprimirPila = new javax.swing.JButton();
        recorrerAtras = new javax.swing.JButton();
        recorrerAdelante = new javax.swing.JButton();
        elementoActual = new javax.swing.JButton();
        textoPantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        agregarPila.setText("Agregar al historial");
        agregarPila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPilaActionPerformed(evt);
            }
        });

        imprimirPila.setText("Historial");
        imprimirPila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirPilaActionPerformed(evt);
            }
        });

        recorrerAtras.setText("Atrás");
        recorrerAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recorrerAtrasActionPerformed(evt);
            }
        });

        recorrerAdelante.setText("Adelante");
        recorrerAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recorrerAdelanteActionPerformed(evt);
            }
        });

        elementoActual.setText("Pag. Actual");
        elementoActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elementoActualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(textoPantalla)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(recorrerAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(elementoActual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(recorrerAdelante))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(imprimirPila))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(agregarPila)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(agregarPila)
                .addGap(18, 18, 18)
                .addComponent(imprimirPila)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recorrerAtras)
                    .addComponent(elementoActual)
                    .addComponent(recorrerAdelante))
                .addGap(23, 23, 23)
                .addComponent(textoPantalla)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recorrerAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recorrerAdelanteActionPerformed
        i = pila.recorrerAdelante(i);
        if(i>i2){
            pila.agregarPaginas(JOptionPane.showInputDialog("Ingrese el nombre de la nueva pagina: "));
            i2 ++;
        }
        textoPantalla.setText(pila.recorrerPila(i));
    }//GEN-LAST:event_recorrerAdelanteActionPerformed

    private void recorrerAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recorrerAtrasActionPerformed
        i = pila.recorrerAtras(i);
        textoPantalla.setText(pila.recorrerPila(i));
    }//GEN-LAST:event_recorrerAtrasActionPerformed

    private void agregarPilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPilaActionPerformed
        pila.agregarPaginas(JOptionPane.showInputDialog("Inserte la Página: "));
        i2 ++;
        i++;
    }//GEN-LAST:event_agregarPilaActionPerformed

    private void imprimirPilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirPilaActionPerformed
        pila.imprimir();
    }//GEN-LAST:event_imprimirPilaActionPerformed

    private void elementoActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elementoActualActionPerformed
        textoPantalla.setText(pila.actual());
        i=i2;
    }//GEN-LAST:event_elementoActualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarPila;
    private javax.swing.JButton elementoActual;
    private javax.swing.JButton imprimirPila;
    private javax.swing.JButton recorrerAdelante;
    private javax.swing.JButton recorrerAtras;
    private javax.swing.JLabel textoPantalla;
    // End of variables declaration//GEN-END:variables
}
