/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.colasejercicio;

import java.util.LinkedList;
import java.util.Queue;
import javax.swing.JOptionPane;

/**
 *
 * @author SCIS2-27
 */
public class Vista extends javax.swing.JFrame {
Queue<String> lista = new LinkedList<>();

    int dinero = 0;
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarCliente = new javax.swing.JButton();
        atenderCliente = new javax.swing.JButton();
        verSiguiente = new javax.swing.JButton();
        revisarClientes = new javax.swing.JButton();
        dineroRecaudado = new javax.swing.JButton();
        recaudo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        agregarCliente.setText("Agregar Cliente");
        agregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarClienteActionPerformed(evt);
            }
        });

        atenderCliente.setText("Atender Cliente");
        atenderCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atenderClienteActionPerformed(evt);
            }
        });

        verSiguiente.setText("Ver siguiente Cliente");
        verSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verSiguienteActionPerformed(evt);
            }
        });

        revisarClientes.setText("Revisar si hay Clientes");
        revisarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revisarClientesActionPerformed(evt);
            }
        });

        dineroRecaudado.setText("Dinero Recaudado");
        dineroRecaudado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dineroRecaudadoActionPerformed(evt);
            }
        });

        recaudo.setText("$0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(atenderCliente)
                            .addComponent(agregarCliente)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(revisarClientes)
                            .addComponent(verSiguiente)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(dineroRecaudado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(recaudo)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(agregarCliente)
                .addGap(18, 18, 18)
                .addComponent(atenderCliente)
                .addGap(18, 18, 18)
                .addComponent(verSiguiente)
                .addGap(18, 18, 18)
                .addComponent(revisarClientes)
                .addGap(18, 18, 18)
                .addComponent(dineroRecaudado)
                .addGap(18, 18, 18)
                .addComponent(recaudo)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarClienteActionPerformed
        String elemento =JOptionPane.showInputDialog("Ingrese el nombre del Cliente");
        lista.add(elemento);
    }//GEN-LAST:event_agregarClienteActionPerformed

    private void atenderClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atenderClienteActionPerformed
        
        if(lista.peek()!=null){
            dinero += Integer.parseInt(JOptionPane.showInputDialog("Valor a cobrar para: "+lista.poll()));
        }else{
            JOptionPane.showMessageDialog(null,"Todos los clientes atendidos");
        }
        
    }//GEN-LAST:event_atenderClienteActionPerformed

    private void verSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verSiguienteActionPerformed
        if(lista.peek()!=null){
            JOptionPane.showMessageDialog(null,"Siguiente en la lista: "+lista.peek());
        }else{
            JOptionPane.showMessageDialog(null,"No hay siguiente");
        }
        
    }//GEN-LAST:event_verSiguienteActionPerformed

    private void revisarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revisarClientesActionPerformed
        if(lista.peek()!=null){
            JOptionPane.showMessageDialog(null,lista);
        }else{
            JOptionPane.showMessageDialog(null,"Lista Vacía");
        }
    }//GEN-LAST:event_revisarClientesActionPerformed

    private void dineroRecaudadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dineroRecaudadoActionPerformed
        recaudo.setText("$"+dinero);
    }//GEN-LAST:event_dineroRecaudadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarCliente;
    private javax.swing.JButton atenderCliente;
    private javax.swing.JButton dineroRecaudado;
    private javax.swing.JLabel recaudo;
    private javax.swing.JButton revisarClientes;
    private javax.swing.JButton verSiguiente;
    // End of variables declaration//GEN-END:variables
}
